### ISSUE TITLE
Plugin causes errors

### ISSUE THREAD

**Issue by AndreasReitberger** [Frosty-Media/frosty-media#3]
Hi,
The plugin causes follwoing errors.

<em>[Sat Mar 14 12:54:34.654956 2015] [fcgid:warn] [pid 7989] [client] mod_fcgid: stderr: PHP Fatal error: Cannot redeclare class WP_GitHub_Updater in /var/www/vhosts/wdbase.de/httpdocs/wp-content/plugins/frosty-media/includes/libraries/github-updater/updater.php on line 34, referer: http://wdbase.de/wp-admin/post.php?post=1688&action=edit&message=10</em>

regards,
Andreas

**Comment by thefrosty** [comment]
If you check that file it checks to make sure said class doesn't exist first. Do you have another plugin that is using a incorrect version if the Github updater plugin?

**Comment by AndreasReitberger** [comment]
Thanks for your reply. Yes I'm using that plugin.
https://github.com/envato/envato-wordpress-toolkit

**Comment by thefrosty** [comment]
Hmm, that's strange, I'll install this and see what I can find out.

**Comment by AndreasReitberger** [comment]
Does the same happen on your and?
Thanks!
