### ISSUE TITLE
Wordpress white page when activing Frosty-Media licence manager.

### ISSUE THREAD

**Issue by JPerguet** [Frosty-Media/frosty-media#4]
It seems i just applied a plugging update. They are requesting the frosty-media Licence manager.
When activating it, the wordpress site is out of control (white page). I need to desinstall the Frosty Media folder in WP-Content to have the site starting again.
And different pluggins requesting the Frosty Manager such as the WP-Masonry Layout not running.

Please, send me an update or how to process.

**Comment by thefrosty** [comment]
Looks like there is some issues with the updater not removing old files correctly. Renaming the plugin via SFTP or deleting would be fine.

**Comment by JPerguet** [comment]
Hello,

I did it twice.
Problem still remaining.

Occurs when activing the plugin.

Other idea ?

Thank you

Jean.
